[INFO   ] Logger: Record log in /storage/emulated/0/Controle financeiro v0.1/.kivy/logs/kivy_22-12-01_4.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] KivyMD: 1.1.1, git-Unknown, 2022-11-05 (installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 v1.r25p1-01bet0.###other-sha0123456789ABCDEF0###'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-G52'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[WARNING] Lang: The file /storage/emulated/0/Controle financeiro v0.1/main.kv is loaded multiples times, you might have unwanted behaviors.
[WARNING] Factory: Ignored class "DrawerClickableItem" re-declaration. Current -  module: None, cls: <class 'kivy.factory.DrawerClickableItem'>, baseclass: MDNavigationDrawerItem, filename: /storage/emulated/0/Controle financeiro v0.1/main.kv. Ignored -  module: None, cls: None, baseclass: MDNavigationDrawerItem, filename: /storage/emulated/0/Controle financeiro v0.1/main.kv.
[WARNING] Factory: Ignored class "DrawerLabelItem" re-declaration. Current -  module: None, cls: None, baseclass: MDNavigationDrawerItem, filename: /storage/emulated/0/Controle financeiro v0.1/main.kv. Ignored -  module: None, cls: None, baseclass: MDNavigationDrawerItem, filename: /storage/emulated/0/Controle financeiro v0.1/main.kv.
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Loader: using a thread pool of 2 workers
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Controle financeiro v0.1/main.py", line 635, in <module>
[WARNING] stderr:     MainApp().run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/app.py", line 950, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/base.py", line 582, in runTouchApp
[WARNING] stderr:     EventLoop.mainloop()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/base.py", line 347, in mainloop
[WARNING] stderr:     self.idle()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/base.py", line 399, in idle
[WARNING] stderr:     Clock.tick_draw()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/clock.py", line 783, in tick_draw
[WARNING] stderr:     self._process_events_before_frame()
[WARNING] stderr:   File "kivy/_clock.pyx", line 658, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 701, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 697, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/label.py", line 409, in texture_update
[WARNING] stderr:     self._label.texture.bind()
[WARNING] stderr:   File "kivy/graphics/texture.pyx", line 765, in kivy.graphics.texture.Texture.bind
[WARNING] stderr:   File "kivy/graphics/texture.pyx", line 790, in kivy.graphics.texture.Texture.bind
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 754, in _texture_fill
[WARNING] stderr:     self.render(real=True)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/markup.py", line 143, in render
[WARNING] stderr:     ret = self._render_real()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/__init__.py", line 681, in _render_real
[WARNING] stderr:     data = self._render_end()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/core/text/text_sdl2.py", line 50, in _render_end
[WARNING] stderr:     return self._surface.get_data()
[WARNING] stderr:   File "kivy/core/text/_text_sdl2.pyx", line 144, in kivy.core.text._text_sdl2._SurfaceContainer.get_data
[WARNING] stderr: MemoryError
